# Generated by Django 4.0.4 on 2022-06-05 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_name', models.CharField(max_length=100)),
                ('exhibition_start_date', models.DateField()),
                ('exhibition_end_date', models.DateField()),
                ('exhibition_ticket_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionStall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_price', models.FloatField()),
                ('stall_name', models.CharField(max_length=100)),
                ('stall_banner', models.FileField(null=True, upload_to='')),
                ('stall_pdf', models.FileField(null=True, upload_to='')),
                ('stall_video', models.FileField(null=True, upload_to='')),
                ('stall_model', models.FileField(null=True, upload_to='')),
                ('stall_exhibition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='StallPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_payment_date', models.DateTimeField(auto_now_add=True)),
                ('stall_payment_amount', models.FloatField()),
                ('stall_payment_exhibition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibition')),
                ('stall_payment_exhibition_stall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibitionstall')),
                ('stall_payment_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibitioncategory'),
        ),
    ]
