# Generated by Django 4.0.4 on 2022-06-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionstall',
            name='stall_banner',
        ),
        migrations.RemoveField(
            model_name='exhibitionstall',
            name='stall_model',
        ),
        migrations.RemoveField(
            model_name='exhibitionstall',
            name='stall_pdf',
        ),
        migrations.RemoveField(
            model_name='exhibitionstall',
            name='stall_video',
        ),
        migrations.AddField(
            model_name='exhibitionstall',
            name='stall_status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StallVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_video', models.FileField(null=True, upload_to='')),
                ('video_status', models.IntegerField(default=0)),
                ('stall_video_stall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibitionstall')),
            ],
        ),
        migrations.CreateModel(
            name='StallPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_pdf', models.FileField(null=True, upload_to='')),
                ('pdf_status', models.IntegerField(default=0)),
                ('stall_pdf_stall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibitionstall')),
            ],
        ),
        migrations.CreateModel(
            name='StallLeaflet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_leaflet_img', models.FileField(null=True, upload_to='')),
                ('leaflet_status', models.IntegerField(default=0)),
                ('stall_leaflet_stall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibitionstall')),
            ],
        ),
        migrations.CreateModel(
            name='StallBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_banner_img', models.FileField(null=True, upload_to='')),
                ('banner_status', models.IntegerField(default=0)),
                ('stall_banner_stall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibitionstall')),
            ],
        ),
        migrations.CreateModel(
            name='CustomStall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customized_name', models.CharField(max_length=100)),
                ('customized_stall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibitionstall')),
            ],
        ),
    ]
