# Generated by Django 4.0.4 on 2022-06-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibition', '0002_remove_exhibitionstall_stall_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionstall',
            name='stall_name',
        ),
    ]
