# Generated by Django 4.0.4 on 2022-06-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibition', '0003_remove_exhibitionstall_stall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionstall',
            name='stall_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
