# Generated by Django 4.0.4 on 2022-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibition', '0004_exhibitionstall_stall_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stallpayments',
            old_name='stall_payment_amount',
            new_name='stall_payment_total_amount',
        ),
        migrations.AddField(
            model_name='stallpayments',
            name='stall_payment_banner',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stallpayments',
            name='stall_payment_leaflet',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stallpayments',
            name='stall_payment_model',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stallpayments',
            name='stall_payment_pdf',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stallpayments',
            name='stall_payment_video',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stallpayments',
            name='stall_payment_video_conf',
            field=models.FloatField(null=True),
        ),
    ]
