# Generated by Django 4.0.4 on 2022-06-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibition', '0005_rename_stall_payment_amount_stallpayments_stall_payment_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_model', models.FileField(null=True, upload_to='')),
                ('model_status', models.IntegerField(default=0)),
                ('stall_lmodel_stall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Exhibition.exhibitionstall')),
            ],
        ),
    ]
