# Generated by Django 4.0.4 on 2022-06-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibition', '0007_customstall_stall_customized_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('event_desc', models.CharField(max_length=100, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
            ],
        ),
    ]
