# Generated by Django 4.0.4 on 2022-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExhibitionAuth', '0002_exhibitor_exhibitor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='exhibitor_address',
            field=models.CharField(max_length=300),
        ),
    ]
